apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roolrd-basic-cluster
  region: eu-central-1
 
#vpc:
# subnets:
#   private:
#      eu-central-1a: { id: subnet-9d6eb6f7 }
#      eu-central-1b: { id: subnet-ab3523d6 }
#      eu-central-1c: { id: subnet-ab3523d6 }

nodeGroups:
  - name: worker-ng-1
    instanceType: t2.micro
    desiredCapacity: 2
  - name: worker-ng-2
    instanceType: t2.micro
    desiredCapacity: 2
